//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySets6C78ED914D4857D0641722593A6A0161CDB13CC6C3D141B987FC8E8A49478FEB))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// Тип содержит представления для наборов EntitySets и AssociationSets, созданные во время разработки.
    /// </Summary>
    public sealed class ViewsForBaseEntitySets6C78ED914D4857D0641722593A6A0161CDB13CC6C3D141B987FC8E8A49478FEB : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// Конструктор хранит представления для экстентов и значения хэша, созданные на основе замыканий и представлений метаданных и сопоставлений.
        /// </Summary>
        public ViewsForBaseEntitySets6C78ED914D4857D0641722593A6A0161CDB13CC6C3D141B987FC8E8A49478FEB()
        {
            this.EdmEntityContainerName = "bdBusEntities";
            this.StoreEntityContainerName = "Хранилище bdBusModelContainer";
            this.HashOverMappingClosure = "b5cdaeaa91df32b09e2371f50a4a761a69f490f6e55afdf4993aff32c09a619b";
            this.HashOverAllExtentViews = "c7ab0cac4b6547f46c43bee3f28347a459dd562b0e3008ab26b4099a0616f56d";
            this.ViewCount = 34;
        }
        
        /// <Summary>
        /// Метод возвращает представление для указанного индекса.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            if ((index == 32))
            {
                return GetView32();
            }
            if ((index == 33))
            {
                return GetView33();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.aBus
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.aBus", @"
    SELECT VALUE -- Constructing aBus
        [Хранилище bdBusModel.aBus](T1.aBus_Id, T1.aBus_Longitude, T1.aBus_Latitude, T1.aBus_Speed, T1.aBus_Azimuth, T1.aBus_DateUpdate, T1.[aBus.Id_bus])
    FROM (
        SELECT 
            T.Id AS aBus_Id, 
            T.Longitude AS aBus_Longitude, 
            T.Latitude AS aBus_Latitude, 
            T.Speed AS aBus_Speed, 
            T.Azimuth AS aBus_Azimuth, 
            T.DateUpdate AS aBus_DateUpdate, 
            T.Id_bus AS [aBus.Id_bus], 
            True AS _from0
        FROM bdBusEntities.aBus AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.aBus
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.aBus", @"
    SELECT VALUE -- Constructing aBus
        [bdBusModel.aBus](T1.aBus_Id, T1.aBus_Longitude, T1.aBus_Latitude, T1.aBus_Speed, T1.aBus_Azimuth, T1.aBus_DateUpdate, T1.[aBus.Id_bus])
    FROM (
        SELECT 
            T.Id AS aBus_Id, 
            T.Longitude AS aBus_Longitude, 
            T.Latitude AS aBus_Latitude, 
            T.Speed AS aBus_Speed, 
            T.Azimuth AS aBus_Azimuth, 
            T.DateUpdate AS aBus_DateUpdate, 
            T.Id_bus AS [aBus.Id_bus], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].aBus AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.Big_Location
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.Big_Location", @"
    SELECT VALUE -- Constructing Big_Location
        [Хранилище bdBusModel.Big_Location](T1.[Big_Location.Id_big], T1.[Big_Location.id_koord1], T1.[Big_Location.id_koord2], T1.[Big_Location.length])
    FROM (
        SELECT 
            T.Id_big AS [Big_Location.Id_big], 
            T.id_koord1 AS [Big_Location.id_koord1], 
            T.id_koord2 AS [Big_Location.id_koord2], 
            T.length AS [Big_Location.length], 
            True AS _from0
        FROM bdBusEntities.Big_Location AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sBuses
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sBuses", @"
    SELECT VALUE -- Constructing sBuses
        [Хранилище bdBusModel.sBuses](T1.sBuses_id, T1.[sBuses.id_marsh], T1.sBuses_nom, T1.[sBuses.marka_ts])
    FROM (
        SELECT 
            T.id AS sBuses_id, 
            T.id_marsh AS [sBuses.id_marsh], 
            T.nom AS sBuses_nom, 
            T.marka_ts AS [sBuses.marka_ts], 
            True AS _from0
        FROM bdBusEntities.sBuses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sKoord_point
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sKoord_point", @"
    SELECT VALUE -- Constructing sKoord_point
        [Хранилище bdBusModel.sKoord_point](T1.[sKoord_point.id], T1.[sKoord_point.Longitude], T1.[sKoord_point.Latitude])
    FROM (
        SELECT 
            T.id AS [sKoord_point.id], 
            T.Longitude AS [sKoord_point.Longitude], 
            T.Latitude AS [sKoord_point.Latitude], 
            True AS _from0
        FROM bdBusEntities.sKoord_point AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sLocation
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sLocation", @"
    SELECT VALUE -- Constructing sLocation
        [Хранилище bdBusModel.sLocation](T1.sLocation_Id, T1.[sLocation.Id_point1], T1.[sLocation.Id_point2], T1.[sLocation.Id_name_location], T1.sLocation_length, T1.sLocation_azimuth, T1.[sLocation.id_big])
    FROM (
        SELECT 
            T.Id AS sLocation_Id, 
            T.Id_point1 AS [sLocation.Id_point1], 
            T.Id_point2 AS [sLocation.Id_point2], 
            T.Id_name_location AS [sLocation.Id_name_location], 
            T.length AS sLocation_length, 
            T.azimuth AS sLocation_azimuth, 
            T.id_big AS [sLocation.id_big], 
            True AS _from0
        FROM bdBusEntities.sLocation AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sLocation_Name
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sLocation_Name", @"
    SELECT VALUE -- Constructing sLocation_Name
        [Хранилище bdBusModel.sLocation_Name](T1.[sLocation_Name.Id_Location_Name], T1.[sLocation_Name.Location_Name])
    FROM (
        SELECT 
            T.Id_Location_Name AS [sLocation_Name.Id_Location_Name], 
            T.Location_Name AS [sLocation_Name.Location_Name], 
            True AS _from0
        FROM bdBusEntities.sLocation_Name AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sMarhList
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sMarhList", @"
    SELECT VALUE -- Constructing sMarhList
        [Хранилище bdBusModel.sMarhList](T1.sMarhList_Id, T1.[sMarhList.Id_Location], T1.[sMarhList.Id_Marsh])
    FROM (
        SELECT 
            T.Id AS sMarhList_Id, 
            T.Id_Location AS [sMarhList.Id_Location], 
            T.Id_Marsh AS [sMarhList.Id_Marsh], 
            True AS _from0
        FROM bdBusEntities.sMarhList AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sMarshruts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sMarshruts", @"
    SELECT VALUE -- Constructing sMarshruts
        [Хранилище bdBusModel.sMarshruts](T1.sMarshruts_id, T1.[sMarshruts.name_marshrut], T1.sMarshruts_type, T1.sMarshruts_num)
    FROM (
        SELECT 
            T.id AS sMarshruts_id, 
            T.name_marshrut AS [sMarshruts.name_marshrut], 
            T.type AS sMarshruts_type, 
            T.num AS sMarshruts_num, 
            True AS _from0
        FROM bdBusEntities.sMarshruts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sName_to_ost
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sName_to_ost", @"
    SELECT VALUE -- Constructing sName_to_ost
        [Хранилище bdBusModel.sName_to_ost](T1.[sName_to_ost.id], T1.[sName_to_ost.idName], T1.[sName_to_ost.idOst])
    FROM (
        SELECT 
            T.id AS [sName_to_ost.id], 
            T.idName AS [sName_to_ost.idName], 
            T.idOst AS [sName_to_ost.idOst], 
            True AS _from0
        FROM bdBusEntities.sName_to_ost AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sOst_name
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sOst_name", @"
    SELECT VALUE -- Constructing sOst_name
        [Хранилище bdBusModel.sOst_name](T1.[sOst_name.id], T1.[sOst_name.name_ost])
    FROM (
        SELECT 
            T.id AS [sOst_name.id], 
            T.name_ost AS [sOst_name.name_ost], 
            True AS _from0
        FROM bdBusEntities.sOst_name AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sOstnovkis
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sOstnovkis", @"
    SELECT VALUE -- Constructing sOstnovkis
        [Хранилище bdBusModel.sOstnovkis](T1.sOstnovkis_id, T1.sOstnovkis_idKoord, T1.sOstnovkis_idMarsh, T1.sOstnovkis_type)
    FROM (
        SELECT 
            T.id AS sOstnovkis_id, 
            T.idKoord AS sOstnovkis_idKoord, 
            T.idMarsh AS sOstnovkis_idMarsh, 
            T.type AS sOstnovkis_type, 
            True AS _from0
        FROM bdBusEntities.sOstnovkis AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.Big_Location
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.Big_Location", @"
    SELECT VALUE -- Constructing Big_Location
        [bdBusModel.Big_Location](T1.[Big_Location.Id_big], T1.[Big_Location.id_koord1], T1.[Big_Location.id_koord2], T1.[Big_Location.length])
    FROM (
        SELECT 
            T.Id_big AS [Big_Location.Id_big], 
            T.id_koord1 AS [Big_Location.id_koord1], 
            T.id_koord2 AS [Big_Location.id_koord2], 
            T.length AS [Big_Location.length], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].Big_Location AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sBuses
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sBuses", @"
    SELECT VALUE -- Constructing sBuses
        [bdBusModel.sBuses](T1.sBuses_id, T1.[sBuses.id_marsh], T1.sBuses_nom, T1.[sBuses.marka_ts])
    FROM (
        SELECT 
            T.id AS sBuses_id, 
            T.id_marsh AS [sBuses.id_marsh], 
            T.nom AS sBuses_nom, 
            T.marka_ts AS [sBuses.marka_ts], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sBuses AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sKoord_point
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sKoord_point", @"
    SELECT VALUE -- Constructing sKoord_point
        [bdBusModel.sKoord_point](T1.[sKoord_point.id], T1.[sKoord_point.Longitude], T1.[sKoord_point.Latitude])
    FROM (
        SELECT 
            T.id AS [sKoord_point.id], 
            T.Longitude AS [sKoord_point.Longitude], 
            T.Latitude AS [sKoord_point.Latitude], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sKoord_point AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sLocation
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sLocation", @"
    SELECT VALUE -- Constructing sLocation
        [bdBusModel.sLocation](T1.sLocation_Id, T1.[sLocation.Id_point1], T1.[sLocation.Id_point2], T1.[sLocation.Id_name_location], T1.sLocation_length, T1.sLocation_azimuth, T1.[sLocation.id_big])
    FROM (
        SELECT 
            T.Id AS sLocation_Id, 
            T.Id_point1 AS [sLocation.Id_point1], 
            T.Id_point2 AS [sLocation.Id_point2], 
            T.Id_name_location AS [sLocation.Id_name_location], 
            T.length AS sLocation_length, 
            T.azimuth AS sLocation_azimuth, 
            T.id_big AS [sLocation.id_big], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sLocation AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sLocation_Name
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sLocation_Name", @"
    SELECT VALUE -- Constructing sLocation_Name
        [bdBusModel.sLocation_Name](T1.[sLocation_Name.Id_Location_Name], T1.[sLocation_Name.Location_Name])
    FROM (
        SELECT 
            T.Id_Location_Name AS [sLocation_Name.Id_Location_Name], 
            T.Location_Name AS [sLocation_Name.Location_Name], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sLocation_Name AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sMarhList
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sMarhList", @"
    SELECT VALUE -- Constructing sMarhList
        [bdBusModel.sMarhList](T1.sMarhList_Id, T1.[sMarhList.Id_Location], T1.[sMarhList.Id_Marsh])
    FROM (
        SELECT 
            T.Id AS sMarhList_Id, 
            T.Id_Location AS [sMarhList.Id_Location], 
            T.Id_Marsh AS [sMarhList.Id_Marsh], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sMarhList AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sMarshruts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sMarshruts", @"
    SELECT VALUE -- Constructing sMarshruts
        [bdBusModel.sMarshruts](T1.sMarshruts_id, T1.[sMarshruts.name_marshrut], T1.sMarshruts_type, T1.sMarshruts_num)
    FROM (
        SELECT 
            T.id AS sMarshruts_id, 
            T.name_marshrut AS [sMarshruts.name_marshrut], 
            T.type AS sMarshruts_type, 
            T.num AS sMarshruts_num, 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sMarshruts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sName_to_ost
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sName_to_ost", @"
    SELECT VALUE -- Constructing sName_to_ost
        [bdBusModel.sName_to_ost](T1.[sName_to_ost.id], T1.[sName_to_ost.idName], T1.[sName_to_ost.idOst])
    FROM (
        SELECT 
            T.id AS [sName_to_ost.id], 
            T.idName AS [sName_to_ost.idName], 
            T.idOst AS [sName_to_ost.idOst], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sName_to_ost AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sOst_name
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sOst_name", @"
    SELECT VALUE -- Constructing sOst_name
        [bdBusModel.sOst_name](T1.[sOst_name.id], T1.[sOst_name.name_ost])
    FROM (
        SELECT 
            T.id AS [sOst_name.id], 
            T.name_ost AS [sOst_name.name_ost], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sOst_name AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sOstnovkis
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sOstnovkis", @"
    SELECT VALUE -- Constructing sOstnovkis
        [bdBusModel.sOstnovkis](T1.sOstnovkis_id, T1.sOstnovkis_idKoord, T1.sOstnovkis_idMarsh, T1.sOstnovkis_type)
    FROM (
        SELECT 
            T.id AS sOstnovkis_id, 
            T.idKoord AS sOstnovkis_idKoord, 
            T.idMarsh AS sOstnovkis_idMarsh, 
            T.type AS sOstnovkis_type, 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sOstnovkis AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.bz_day
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.bz_day", @"
    SELECT VALUE -- Constructing bz_day
        [Хранилище bdBusModel.bz_day](T1.[bz_day.Id], T1.[bz_day.Days], T1.[bz_day.Times], T1.[bz_day.Location], T1.[bz_day.Kol], T1.[bz_day.Val])
    FROM (
        SELECT 
            T.Id AS [bz_day.Id], 
            T.Days AS [bz_day.Days], 
            T.Times AS [bz_day.Times], 
            T.Location AS [bz_day.Location], 
            T.Kol AS [bz_day.Kol], 
            T.Val AS [bz_day.Val], 
            True AS _from0
        FROM bdBusEntities.bz_day AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.bz_day
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.bz_day", @"
    SELECT VALUE -- Constructing bz_day
        [bdBusModel.bz_day](T1.[bz_day.Id], T1.[bz_day.Days], T1.[bz_day.Times], T1.[bz_day.Location], T1.[bz_day.Kol], T1.[bz_day.Val])
    FROM (
        SELECT 
            T.Id AS [bz_day.Id], 
            T.Days AS [bz_day.Days], 
            T.Times AS [bz_day.Times], 
            T.Location AS [bz_day.Location], 
            T.Kol AS [bz_day.Kol], 
            T.Val AS [bz_day.Val], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].bz_day AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.bz_koeff
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.bz_koeff", @"
    SELECT VALUE -- Constructing bz_koeff
        [Хранилище bdBusModel.bz_koeff](T1.[bz_koeff.Id], T1.[bz_koeff.Location], T1.[bz_koeff.Koeff])
    FROM (
        SELECT 
            T.Id AS [bz_koeff.Id], 
            T.Location AS [bz_koeff.Location], 
            T.Koeff AS [bz_koeff.Koeff], 
            True AS _from0
        FROM bdBusEntities.bz_koeff AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.bz_koeff
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.bz_koeff", @"
    SELECT VALUE -- Constructing bz_koeff
        [bdBusModel.bz_koeff](T1.[bz_koeff.Id], T1.[bz_koeff.Location], T1.[bz_koeff.Koeff])
    FROM (
        SELECT 
            T.Id AS [bz_koeff.Id], 
            T.Location AS [bz_koeff.Location], 
            T.Koeff AS [bz_koeff.Koeff], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].bz_koeff AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.bz_week
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.bz_week", @"
    SELECT VALUE -- Constructing bz_week
        [Хранилище bdBusModel.bz_week](T1.[bz_week.Id], T1.[bz_week.Days], T1.[bz_week.Times], T1.[bz_week.Location], T1.[bz_week.Kol], T1.[bz_week.Val])
    FROM (
        SELECT 
            T.Id AS [bz_week.Id], 
            T.Days AS [bz_week.Days], 
            T.Times AS [bz_week.Times], 
            T.Location AS [bz_week.Location], 
            T.Kol AS [bz_week.Kol], 
            T.Val AS [bz_week.Val], 
            True AS _from0
        FROM bdBusEntities.bz_week AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.bz_week
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.bz_week", @"
    SELECT VALUE -- Constructing bz_week
        [bdBusModel.bz_week](T1.[bz_week.Id], T1.[bz_week.Days], T1.[bz_week.Times], T1.[bz_week.Location], T1.[bz_week.Kol], T1.[bz_week.Val])
    FROM (
        SELECT 
            T.Id AS [bz_week.Id], 
            T.Days AS [bz_week.Days], 
            T.Times AS [bz_week.Times], 
            T.Location AS [bz_week.Location], 
            T.Kol AS [bz_week.Kol], 
            T.Val AS [bz_week.Val], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].bz_week AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.bz_year
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.bz_year", @"
    SELECT VALUE -- Constructing bz_year
        [Хранилище bdBusModel.bz_year](T1.[bz_year.Id], T1.[bz_year.Days], T1.[bz_year.Times], T1.[bz_year.Location], T1.[bz_year.Kol], T1.[bz_year.Val])
    FROM (
        SELECT 
            T.Id AS [bz_year.Id], 
            T.Days AS [bz_year.Days], 
            T.Times AS [bz_year.Times], 
            T.Location AS [bz_year.Location], 
            T.Kol AS [bz_year.Kol], 
            T.Val AS [bz_year.Val], 
            True AS _from0
        FROM bdBusEntities.bz_year AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.bz_year
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.bz_year", @"
    SELECT VALUE -- Constructing bz_year
        [bdBusModel.bz_year](T1.[bz_year.Id], T1.[bz_year.Days], T1.[bz_year.Times], T1.[bz_year.Location], T1.[bz_year.Kol], T1.[bz_year.Val])
    FROM (
        SELECT 
            T.Id AS [bz_year.Id], 
            T.Days AS [bz_year.Days], 
            T.Times AS [bz_year.Times], 
            T.Location AS [bz_year.Location], 
            T.Kol AS [bz_year.Kol], 
            T.Val AS [bz_year.Val], 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].bz_year AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.sHolidays
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.sHolidays", @"
    SELECT VALUE -- Constructing sHolidays
        [Хранилище bdBusModel.sHolidays](T1.sHolidays_Id, T1.sHolidays_DateHolidays, T1.sHolidays_TypeDay)
    FROM (
        SELECT 
            T.Id AS sHolidays_Id, 
            T.DateHolidays AS sHolidays_DateHolidays, 
            T.TypeDay AS sHolidays_TypeDay, 
            True AS _from0
        FROM bdBusEntities.sHolidays AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.sHolidays
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.sHolidays", @"
    SELECT VALUE -- Constructing sHolidays
        [bdBusModel.sHolidays](T1.sHolidays_Id, T1.sHolidays_DateHolidays, T1.sHolidays_TypeDay)
    FROM (
        SELECT 
            T.Id AS sHolidays_Id, 
            T.DateHolidays AS sHolidays_DateHolidays, 
            T.TypeDay AS sHolidays_TypeDay, 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].sHolidays AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для Хранилище bdBusModelContainer.Statist
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView32()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("Хранилище bdBusModelContainer.Statist", @"
    SELECT VALUE -- Constructing Statist
        [Хранилище bdBusModel.Statist](T1.Statist_ID, T1.Statist_sIP, T1.Statist_dDate, T1.Statist_iCount)
    FROM (
        SELECT 
            T.ID AS Statist_ID, 
            T.sIP AS Statist_sIP, 
            T.dDate AS Statist_dDate, 
            T.iCount AS Statist_iCount, 
            True AS _from0
        FROM bdBusEntities.Statist AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// возвратить представление для bdBusEntities.Statist
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView33()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("bdBusEntities.Statist", @"
    SELECT VALUE -- Constructing Statist
        [bdBusModel.Statist](T1.Statist_ID, T1.Statist_sIP, T1.Statist_dDate, T1.Statist_iCount)
    FROM (
        SELECT 
            T.ID AS Statist_ID, 
            T.sIP AS Statist_sIP, 
            T.dDate AS Statist_dDate, 
            T.iCount AS Statist_iCount, 
            True AS _from0
        FROM [Хранилище bdBusModelContainer].Statist AS T
    ) AS T1");
        }
    }
}
