//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sKoord_point
    {
        public sKoord_point()
        {
            this.Big_Location = new HashSet<Big_Location>();
            this.Big_Location1 = new HashSet<Big_Location>();
            this.sLocation = new HashSet<sLocation>();
            this.sLocation1 = new HashSet<sLocation>();
            this.sOstnovkis = new HashSet<sOstnovkis>();
        }
    
        public int id { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
    
        public virtual ICollection<Big_Location> Big_Location { get; set; }
        public virtual ICollection<Big_Location> Big_Location1 { get; set; }
        public virtual ICollection<sLocation> sLocation { get; set; }
        public virtual ICollection<sLocation> sLocation1 { get; set; }
        public virtual ICollection<sOstnovkis> sOstnovkis { get; set; }
    }
}
