//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sLocation
    {
        public sLocation()
        {
            this.sMarhList = new HashSet<sMarhList>();
        }
    
        public int Id { get; set; }
        public int Id_point1 { get; set; }
        public int Id_point2 { get; set; }
        public Nullable<int> Id_name_location { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> azimuth { get; set; }
        public Nullable<int> id_big { get; set; }
    
        public virtual Big_Location Big_Location { get; set; }
        public virtual sKoord_point sKoord_point { get; set; }
        public virtual sKoord_point sKoord_point1 { get; set; }
        public virtual sLocation_Name sLocation_Name { get; set; }
        public virtual ICollection<sMarhList> sMarhList { get; set; }
    }
}
