//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sLocation_Name
    {
        public sLocation_Name()
        {
            this.sLocation = new HashSet<sLocation>();
        }
    
        public int Id_Location_Name { get; set; }
        public string Location_Name { get; set; }
    
        public virtual ICollection<sLocation> sLocation { get; set; }
    }
}
