//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sMarhList
    {
        public int Id { get; set; }
        public int Id_Location { get; set; }
        public int Id_Marsh { get; set; }
    
        public virtual sLocation sLocation { get; set; }
        public virtual sMarshruts sMarshruts { get; set; }
    }
}
