//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sMarshruts
    {
        public sMarshruts()
        {
            this.sBuses = new HashSet<sBuses>();
            this.sMarhList = new HashSet<sMarhList>();
            this.sOstnovkis = new HashSet<sOstnovkis>();
        }
    
        public int id { get; set; }
        public string name_marshrut { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> num { get; set; }
    
        public virtual ICollection<sBuses> sBuses { get; set; }
        public virtual ICollection<sMarhList> sMarhList { get; set; }
        public virtual ICollection<sOstnovkis> sOstnovkis { get; set; }
    }
}
