//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sName_to_ost
    {
        public int id { get; set; }
        public Nullable<int> idName { get; set; }
        public Nullable<int> idOst { get; set; }
    
        public virtual sOst_name sOst_name { get; set; }
        public virtual sOstnovkis sOstnovkis { get; set; }
    }
}
