//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class sOst_name
    {
        public sOst_name()
        {
            this.sName_to_ost = new HashSet<sName_to_ost>();
        }
    
        public int id { get; set; }
        public string name_ost { get; set; }
    
        public virtual ICollection<sName_to_ost> sName_to_ost { get; set; }
    }
}
